import PyQt5.QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import cv2
import time
import sys


sys.path.insert(0, "..")
from controllers.controller import Controller
from controllers.gesture_name_mapper import NameMapper
from controllers.functions_getter import FunctionsGetter
from controllers.system_controller import SystemController


class MyComboBox(PyQt5.QtWidgets.QComboBox):
    '''Class which ignore scroll mouse in QComboBox'''
    def __init__(self, scrollWidget=None, *args, **kwargs):
        super(PyQt5.QtWidgets.QComboBox, self).__init__(*args, **kwargs)
        self.scrollWidget = scrollWidget
        self.setFocusPolicy(QtCore.Qt.StrongFocus)

    def wheelEvent(self, *args, **kwargs):
        if self.hasFocus():
            return QtGui.QComboBox.wheelEvent(self, *args, **kwargs)
        else:
            return self.scrollWidget.wheelEvent(*args, **kwargs)


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.close_time = False
        self.name_mapper = NameMapper()
        self.sys_cont = SystemController()
        self.func_get = FunctionsGetter(self.sys_cont)
        self.cont = Controller(self.func_get, self.sys_cont, self)
        self.sys_cont.set_camera_reference(self.cont.get_camera_controller())
    def refresh_camera_list(self):
        temp = self.cont.get_camera_controller().refresh_camera_list()
        if temp >= 0:
            self.setResolutionCamera_combobox.setCurrentText("Original")
            self.setCamera_combobox.setCurrentText(str(temp))
    def set_camera(self):
        temp=self.cont.get_camera_controller().set_used_camera_number(int(self.setCamera_combobox.currentText()))
        if temp >= 0:
            self.setCamera_combobox.setCurrentText(str(temp))
            self.setResolutionCamera_combobox.setCurrentText("Original")


    def show_handy_started(self):
        self.recognition_in_starttab_label.setText("Gesture recognition enabled")
        self.recognition_in_gesturetab_label.setText("Gesture recognition enabled")
        self.recognition_in_cameratab_label.setText("Gesture recognition enabled")
        self.recognition_in_starttab_label.setStyleSheet("background-color: rgb(0, 255, 0);\n"
                                                             "border: 1px solid black;")
        self.recognition_in_gesturetab_label.setStyleSheet("background-color: rgb(0, 255, 0);\n"
                                                               "border: 1px solid black;")
        self.recognition_in_cameratab_label.setStyleSheet("background-color: rgb(0, 255, 0);\n"
                                                              "border: 1px solid black;")
    def show_handy_stopped(self):
        self.recognition_in_starttab_label.setText("Gesture recognition disabled")
        self.recognition_in_gesturetab_label.setText("Gesture recognition disabled")
        self.recognition_in_cameratab_label.setText("Gesture recognition disabled")
        self.recognition_in_starttab_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                                             "border: 1px solid black;")
        self.recognition_in_gesturetab_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                                               "border: 1px solid black;")
        self.recognition_in_cameratab_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                                              "border: 1px solid black;")
    def open_documentation(self):
        print("documentation opened")
    def show_authors(self):
        print("about authors")
    def get_config(self):
        config = self.cont.get_camera().get_mapping().get_gestures_list()
        self.action1_comboBox.setCurrentText(config.get(1))
        self.action2_comboBox.setCurrentText(config.get(2))
        self.action3_comboBox.setCurrentText(config.get(3))
        self.action4_comboBox.setCurrentText(config.get(4))
        self.action5_comboBox.setCurrentText(config.get(5))
        self.action6_comboBox.setCurrentText(config.get(6))
        self.action7_comboBox.setCurrentText(config.get(7))
        self.action8_comboBox.setCurrentText(config.get(8))
        self.action9_comboBox.setCurrentText(config.get(9))
        self.action10_comboBox.setCurrentText(config.get(10))
        self.action11_comboBox.setCurrentText(config.get(11))
        self.action12_comboBox.setCurrentText(config.get(12))
        self.action13_comboBox.setCurrentText(config.get(13))
        self.action14_comboBox.setCurrentText(config.get(14))
        self.action15_comboBox.setCurrentText(config.get(15))
        self.action16_comboBox.setCurrentText(config.get(16))
        self.action17_comboBox.setCurrentText(config.get(17))
        self.action18_comboBox.setCurrentText(config.get(18))
        self.action19_comboBox.setCurrentText(config.get(19))
        self.action20_comboBox.setCurrentText(config.get(20))
        self.action21_comboBox.setCurrentText(config.get(21))
        self.action22_comboBox.setCurrentText(config.get(22))
        self.action23_comboBox.setCurrentText(config.get(23))
        self.action24_comboBox.setCurrentText(config.get(24))
        self.action25_comboBox.setCurrentText(config.get(25))
    def get_default_config(self):
        self.cont.get_camera().get_mapping().read_default_configuration_from_file()
        self.get_config()
    def set_config(self):
        dict={}
        dict[1] = self.action1_comboBox.currentText()
        dict[2] = self.action2_comboBox.currentText()
        dict[3] = self.action3_comboBox.currentText()
        dict[4] = self.action4_comboBox.currentText()
        dict[5] = self.action5_comboBox.currentText()
        dict[6] = self.action6_comboBox.currentText()
        dict[7] = self.action7_comboBox.currentText()
        dict[8] = self.action8_comboBox.currentText()
        dict[9] = self.action9_comboBox.currentText()
        dict[10] = self.action10_comboBox.currentText()
        dict[11] = self.action11_comboBox.currentText()
        dict[12] = self.action12_comboBox.currentText()
        dict[13] = self.action13_comboBox.currentText()
        dict[14] = self.action14_comboBox.currentText()
        dict[15] = self.action15_comboBox.currentText()
        dict[16] = self.action16_comboBox.currentText()
        dict[17] = self.action17_comboBox.currentText()
        dict[18] = self.action18_comboBox.currentText()
        dict[19] = self.action19_comboBox.currentText()
        dict[20] = self.action20_comboBox.currentText()
        dict[21] = self.action21_comboBox.currentText()
        dict[22] = self.action22_comboBox.currentText()
        dict[23] = self.action23_comboBox.currentText()
        dict[24] = self.action24_comboBox.currentText()
        dict[25] = self.action25_comboBox.currentText()
        self.cont.get_camera().get_mapping().set_gesture(dict)

    def get_controller(self):
        return self.cont

    def get_close_time(self):
        return self.close_time

    def close_application(self):
        self.close_time = True
        self.cont.get_camera_controller().release_camera()
        self.cont.get_camera().get_mapping().end_thread()
        time.sleep(0.1)
        sys.exit(0)

    def set_cameras_combo_box(self, lst):
        self.setCamera_combobox.clear()
        for a in lst:
            self.setCamera_combobox.addItem(str(a))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 846)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 32, 32))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 32, 32))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 32, 32))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 24, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.documentationButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentationButton.sizePolicy().hasHeightForWidth())
        self.documentationButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.documentationButton.setFont(font)
        self.documentationButton.setStyleSheet("background-color: rgb(112, 211, 69);")
        self.documentationButton.setObjectName("documentationButton")
        self.gridLayout_2.addWidget(self.documentationButton, 4, 0, 1, 1)
        self.startHandyButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startHandyButton.sizePolicy().hasHeightForWidth())
        self.startHandyButton.setSizePolicy(sizePolicy)
        self.startHandyButton.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(79, 79, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.startHandyButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.startHandyButton.setFont(font)
        self.startHandyButton.setStyleSheet("background-color: rgb(79, 79, 79);")

        self.startHandyButton.setObjectName("startHandyButton")
        self.gridLayout_2.addWidget(self.startHandyButton, 3, 0, 1, 1)
        self.authorButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorButton.sizePolicy().hasHeightForWidth())
        self.authorButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.authorButton.setFont(font)
        self.authorButton.setStyleSheet("background-color: rgb(79, 79, 79);")
        self.authorButton.setObjectName("authorButton")
        self.gridLayout_2.addWidget(self.authorButton, 4, 1, 1, 1)
        self.recognition_in_starttab_label = QtWidgets.QLabel(self.tab)
        self.recognition_in_starttab_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recognition_in_starttab_label.sizePolicy().hasHeightForWidth())
        self.recognition_in_starttab_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recognition_in_starttab_label.setFont(font)
        self.recognition_in_starttab_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                                         "border: 1px solid black;")
        self.recognition_in_starttab_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.recognition_in_starttab_label.setObjectName("recognition_in_starttab_label")
        self.gridLayout_2.addWidget(self.recognition_in_starttab_label, 0, 0, 1, 1)
        self.stopHandyButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopHandyButton.sizePolicy().hasHeightForWidth())
        self.stopHandyButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.stopHandyButton.setFont(font)
        self.stopHandyButton.setStyleSheet("background-color: rgb(112, 211, 69);")
        self.stopHandyButton.setObjectName("stopHandyButton")
        self.gridLayout_2.addWidget(self.stopHandyButton, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gestureTab = QtWidgets.QWidget()
        self.gestureTab.setObjectName("gestureTab")
        self.gridLayout = QtWidgets.QGridLayout(self.gestureTab)
        self.gridLayout.setObjectName("gridLayout")
        self.recognition_in_gesturetab_label = QtWidgets.QLabel(self.gestureTab)
        self.recognition_in_gesturetab_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recognition_in_gesturetab_label.sizePolicy().hasHeightForWidth())
        self.recognition_in_gesturetab_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recognition_in_gesturetab_label.setFont(font)
        self.recognition_in_gesturetab_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                                           "border: 1px solid black;")
        self.recognition_in_gesturetab_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.recognition_in_gesturetab_label.setObjectName("recognition_in_gesturetab_label")
        self.gridLayout.addWidget(self.recognition_in_gesturetab_label, 0, 4, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.gestureTab)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background-color: rgb(48, 48, 48);\n"
                                      "")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 774, 1238))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_2.setStyleSheet("border: 1px solid black;\n"
                                    "background-color: rgb(112, 211, 69);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gesturename_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gesturename_label.setFont(font)
        self.gesturename_label.setStyleSheet("")
        self.gesturename_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gesturename_label.setObjectName("gesturename_label")
        self.horizontalLayout_5.addWidget(self.gesturename_label)
        self.actionNameLabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.actionNameLabel.setFont(font)
        self.actionNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionNameLabel.setObjectName("actionNameLabel")
        self.horizontalLayout_5.addWidget(self.actionNameLabel)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_7.setStyleSheet("background-color: rgb(79, 79, 79);\n"
                                    "background-color: rgb(111, 111, 111);\n"
                                    "")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pull_hand_in_label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pull_hand_in_label.setFont(font)
        self.pull_hand_in_label.setObjectName("pull_hand_in_label")
        self.horizontalLayout_11.addWidget(self.pull_hand_in_label)
        #self.action1_comboBox = QtWidgets.QComboBox(self.widget_7)
        self.action1_comboBox =MyComboBox(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action1_comboBox.setFont(font)
        self.action1_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action1_comboBox.setObjectName("action1_comboBox")
        self.horizontalLayout_11.addWidget(self.action1_comboBox)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.drumming_fingers_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.drumming_fingers_label.setFont(font)
        self.drumming_fingers_label.setObjectName("drumming_fingers_label")
        self.horizontalLayout_4.addWidget(self.drumming_fingers_label)
        #self.action2_comboBox = QtWidgets.QComboBox(self.widget)
        self.action2_comboBox=MyComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action2_comboBox.setFont(font)
        self.action2_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action2_comboBox.setObjectName("action2_comboBox")
        self.horizontalLayout_4.addWidget(self.action2_comboBox)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_14.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushingTwoFingers_label = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushingTwoFingers_label.setFont(font)
        self.pushingTwoFingers_label.setObjectName("pushingTwoFingers_label")
        self.horizontalLayout_20.addWidget(self.pushingTwoFingers_label)
        self.action3_comboBox = MyComboBox(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action3_comboBox.setFont(font)
        self.action3_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action3_comboBox.setObjectName("action3_comboBox")
        self.horizontalLayout_20.addWidget(self.action3_comboBox)
        self.verticalLayout_2.addWidget(self.widget_14)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_8.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pullingTwoFingersfingers_label = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pullingTwoFingersfingers_label.setFont(font)
        self.pullingTwoFingersfingers_label.setObjectName("pullingTwoFingersfingers_label")
        self.horizontalLayout_12.addWidget(self.pullingTwoFingersfingers_label)
        self.action4_comboBox = MyComboBox(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action4_comboBox.setFont(font)
        self.action4_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action4_comboBox.setObjectName("action4_comboBox")
        self.horizontalLayout_12.addWidget(self.action4_comboBox)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_9.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushinHandAway_label = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushinHandAway_label.setFont(font)
        self.pushinHandAway_label.setObjectName("pushinHandAway_label")
        self.horizontalLayout_13.addWidget(self.pushinHandAway_label)
        self.action5_comboBox = MyComboBox(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action5_comboBox.setFont(font)
        self.action5_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action5_comboBox.setObjectName("action5_comboBox")
        self.horizontalLayout_13.addWidget(self.action5_comboBox)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_11.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.rollingHandForward_label = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rollingHandForward_label.setFont(font)
        self.rollingHandForward_label.setObjectName("rollingHandForward_label")
        self.horizontalLayout_15.addWidget(self.rollingHandForward_label)
        self.action6_comboBox = MyComboBox(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action6_comboBox.setFont(font)
        self.action6_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action6_comboBox.setObjectName("action6_comboBox")
        self.horizontalLayout_15.addWidget(self.action6_comboBox)
        self.verticalLayout_2.addWidget(self.widget_11)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_10.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rollingHandBackward_label = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rollingHandBackward_label.setFont(font)
        self.rollingHandBackward_label.setObjectName("rollingHandBackward_label")
        self.horizontalLayout_14.addWidget(self.rollingHandBackward_label)
        self.action7_comboBox = MyComboBox(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action7_comboBox.setFont(font)
        self.action7_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action7_comboBox.setObjectName("action7_comboBox")
        self.horizontalLayout_14.addWidget(self.action7_comboBox)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_12.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.shakingHand_label = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.shakingHand_label.setFont(font)
        self.shakingHand_label.setObjectName("shakingHand_label")
        self.horizontalLayout_16.addWidget(self.shakingHand_label)
        self.action8_comboBox = MyComboBox(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action8_comboBox.sizePolicy().hasHeightForWidth())
        self.action8_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action8_comboBox.setFont(font)
        self.action8_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action8_comboBox.setObjectName("action8_comboBox")
        self.horizontalLayout_16.addWidget(self.action8_comboBox)
        self.verticalLayout_2.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_13.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.sliding2Down_label = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sliding2Down_label.setFont(font)
        self.sliding2Down_label.setObjectName("sliding2Down_label")
        self.horizontalLayout_17.addWidget(self.sliding2Down_label)
        self.action9_comboBox = MyComboBox(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action9_comboBox.sizePolicy().hasHeightForWidth())
        self.action9_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action9_comboBox.setFont(font)
        self.action9_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                            "border: 1px solid black;")
        self.action9_comboBox.setObjectName("action9_comboBox")
        self.horizontalLayout_17.addWidget(self.action9_comboBox)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.widget_15 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_15.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.sliding2left_label = QtWidgets.QLabel(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sliding2left_label.setFont(font)
        self.sliding2left_label.setObjectName("sliding2left_label")
        self.horizontalLayout_23.addWidget(self.sliding2left_label)
        self.action10_comboBox = MyComboBox(self.widget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action10_comboBox.setFont(font)
        self.action10_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action10_comboBox.setObjectName("action10_comboBox")
        self.horizontalLayout_23.addWidget(self.action10_comboBox)
        self.verticalLayout_2.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_16.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.sliding2right_label = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sliding2right_label.setFont(font)
        self.sliding2right_label.setObjectName("sliding2right_label")
        self.horizontalLayout_24.addWidget(self.sliding2right_label)
        self.action11_comboBox = MyComboBox(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action11_comboBox.setFont(font)
        self.action11_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action11_comboBox.setObjectName("action11_comboBox")
        self.horizontalLayout_24.addWidget(self.action11_comboBox)
        self.verticalLayout_2.addWidget(self.widget_16)
        self.widget_26 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_26.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.widget_26)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.sliding2up_label = QtWidgets.QLabel(self.widget_26)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sliding2up_label.setFont(font)
        self.sliding2up_label.setObjectName("sliding2up_label")
        self.horizontalLayout_34.addWidget(self.sliding2up_label)
        self.action12_comboBox = MyComboBox(self.widget_26)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action12_comboBox.setFont(font)
        self.action12_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action12_comboBox.setObjectName("action12_comboBox")
        self.horizontalLayout_34.addWidget(self.action12_comboBox)
        self.verticalLayout_2.addWidget(self.widget_26)
        self.widget_25 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_25.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.widget_25)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.stopSign_label = QtWidgets.QLabel(self.widget_25)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopSign_label.setFont(font)
        self.stopSign_label.setObjectName("stopSign_label")
        self.horizontalLayout_33.addWidget(self.stopSign_label)
        self.action13_comboBox = MyComboBox(self.widget_25)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action13_comboBox.setFont(font)
        self.action13_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action13_comboBox.setObjectName("action13_comboBox")
        self.horizontalLayout_33.addWidget(self.action13_comboBox)
        self.verticalLayout_2.addWidget(self.widget_25)
        self.widget_24 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.widget_24.setFont(font)
        self.widget_24.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.swipingDown_label = QtWidgets.QLabel(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.swipingDown_label.setFont(font)
        self.swipingDown_label.setObjectName("swipingDown_label")
        self.horizontalLayout_32.addWidget(self.swipingDown_label)
        self.action14_comboBox = MyComboBox(self.widget_24)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action14_comboBox.setFont(font)
        self.action14_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action14_comboBox.setObjectName("action14_comboBox")
        self.horizontalLayout_32.addWidget(self.action14_comboBox)
        self.verticalLayout_2.addWidget(self.widget_24)
        self.widget_23 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_23.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.swipingLeft_label = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.swipingLeft_label.setFont(font)
        self.swipingLeft_label.setObjectName("swipingLeft_label")
        self.horizontalLayout_31.addWidget(self.swipingLeft_label)
        self.action15_comboBox = MyComboBox(self.widget_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action15_comboBox.setFont(font)
        self.action15_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action15_comboBox.setObjectName("action15_comboBox")
        self.horizontalLayout_31.addWidget(self.action15_comboBox)
        self.verticalLayout_2.addWidget(self.widget_23)
        self.widget_22 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_22.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.swipingRight_label = QtWidgets.QLabel(self.widget_22)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.swipingRight_label.setFont(font)
        self.swipingRight_label.setObjectName("swipingRight_label")
        self.horizontalLayout_30.addWidget(self.swipingRight_label)
        self.action16_comboBox = MyComboBox(self.widget_22)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action16_comboBox.setFont(font)
        self.action16_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action16_comboBox.setObjectName("action16_comboBox")
        self.horizontalLayout_30.addWidget(self.action16_comboBox)
        self.verticalLayout_2.addWidget(self.widget_22)
        self.widget_21 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_21.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.swipingUp_label = QtWidgets.QLabel(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.swipingUp_label.setFont(font)
        self.swipingUp_label.setObjectName("swipingUp_label")
        self.horizontalLayout_29.addWidget(self.swipingUp_label)
        self.action17_comboBox = MyComboBox(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action17_comboBox.setFont(font)
        self.action17_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action17_comboBox.setObjectName("action17_comboBox")
        self.horizontalLayout_29.addWidget(self.action17_comboBox)
        self.verticalLayout_2.addWidget(self.widget_21)
        self.widget_20 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_20.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.thumbDown_label = QtWidgets.QLabel(self.widget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.thumbDown_label.setFont(font)
        self.thumbDown_label.setObjectName("thumbDown_label")
        self.horizontalLayout_28.addWidget(self.thumbDown_label)
        self.action18_comboBox = MyComboBox(self.widget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action18_comboBox.setFont(font)
        self.action18_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action18_comboBox.setObjectName("action18_comboBox")
        self.horizontalLayout_28.addWidget(self.action18_comboBox)
        self.verticalLayout_2.addWidget(self.widget_20)
        self.widget_19 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_19.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.ThumbUp_label = QtWidgets.QLabel(self.widget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ThumbUp_label.setFont(font)
        self.ThumbUp_label.setObjectName("ThumbUp_label")
        self.horizontalLayout_27.addWidget(self.ThumbUp_label)
        self.action19_comboBox = MyComboBox(self.widget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action19_comboBox.setFont(font)
        self.action19_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action19_comboBox.setObjectName("action19_comboBox")
        self.horizontalLayout_27.addWidget(self.action19_comboBox)
        self.verticalLayout_2.addWidget(self.widget_19)
        self.widget_17 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_17.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.turningHandClockwise_label = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.turningHandClockwise_label.setFont(font)
        self.turningHandClockwise_label.setObjectName("turningHandClockwise_label")
        self.horizontalLayout_25.addWidget(self.turningHandClockwise_label)
        self.action20_comboBox = MyComboBox(self.widget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action20_comboBox.setFont(font)
        self.action20_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action20_comboBox.setObjectName("action20_comboBox")
        self.horizontalLayout_25.addWidget(self.action20_comboBox)
        self.verticalLayout_2.addWidget(self.widget_17)
        self.widget_31 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_31.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_31.setObjectName("widget_31")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.widget_31)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.turningHandcounterclockwise_label = QtWidgets.QLabel(self.widget_31)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.turningHandcounterclockwise_label.setFont(font)
        self.turningHandcounterclockwise_label.setObjectName("turningHandcounterclockwise_label")
        self.horizontalLayout_39.addWidget(self.turningHandcounterclockwise_label)
        self.action21_comboBox = MyComboBox(self.widget_31)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action21_comboBox.setFont(font)
        self.action21_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action21_comboBox.setObjectName("action21_comboBox")
        self.horizontalLayout_39.addWidget(self.action21_comboBox)
        self.verticalLayout_2.addWidget(self.widget_31)
        self.widget_30 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_30.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.zoomingInWithFull_label = QtWidgets.QLabel(self.widget_30)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zoomingInWithFull_label.setFont(font)
        self.zoomingInWithFull_label.setObjectName("zoomingInWithFull_label")
        self.horizontalLayout_38.addWidget(self.zoomingInWithFull_label)
        self.action22_comboBox = MyComboBox(self.widget_30)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action22_comboBox.setFont(font)
        self.action22_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action22_comboBox.setObjectName("action22_comboBox")
        self.horizontalLayout_38.addWidget(self.action22_comboBox)
        self.verticalLayout_2.addWidget(self.widget_30)
        self.widget_29 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_29.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_29.setObjectName("widget_29")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.widget_29)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.zoomingInWith2_label = QtWidgets.QLabel(self.widget_29)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zoomingInWith2_label.setFont(font)
        self.zoomingInWith2_label.setObjectName("zoomingInWith2_label")
        self.horizontalLayout_37.addWidget(self.zoomingInWith2_label)
        self.action23_comboBox = MyComboBox(self.widget_29)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action23_comboBox.setFont(font)
        self.action23_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action23_comboBox.setObjectName("action23_comboBox")
        self.horizontalLayout_37.addWidget(self.action23_comboBox)
        self.verticalLayout_2.addWidget(self.widget_29)
        self.widget_28 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_28.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_28.setObjectName("widget_28")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.widget_28)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.zoomingOutWithFull_label = QtWidgets.QLabel(self.widget_28)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zoomingOutWithFull_label.setFont(font)
        self.zoomingOutWithFull_label.setObjectName("zoomingOutWithFull_label")
        self.horizontalLayout_36.addWidget(self.zoomingOutWithFull_label)
        self.action24_comboBox = MyComboBox(self.widget_28)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action24_comboBox.setFont(font)
        self.action24_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action24_comboBox.setObjectName("action24_comboBox")
        self.horizontalLayout_36.addWidget(self.action24_comboBox)
        self.verticalLayout_2.addWidget(self.widget_28)
        self.widget_27 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_27.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.zoomingOutWith2_label = QtWidgets.QLabel(self.widget_27)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.zoomingOutWith2_label.setFont(font)
        self.zoomingOutWith2_label.setObjectName("zoomingOutWith2_label")
        self.horizontalLayout_35.addWidget(self.zoomingOutWith2_label)
        self.action25_comboBox = MyComboBox(self.widget_27)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action25_comboBox.setFont(font)
        self.action25_comboBox.setStyleSheet("background-color: rgb(171, 171, 171);\n"
                                             "border: 1px solid black;")
        self.action25_comboBox.setObjectName("action25_comboBox")
        self.horizontalLayout_35.addWidget(self.action25_comboBox)
        self.verticalLayout_2.addWidget(self.widget_27)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 5, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cancelButton = QtWidgets.QPushButton(self.gestureTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setMinimumSize(QtCore.QSize(120, 60))
        self.cancelButton.setBaseSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("background-color: rgb(112, 211, 69);")

        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.resetButton = QtWidgets.QPushButton(self.gestureTab)
        self.resetButton.setMinimumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background-color: rgb(112, 211, 69);")

        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_3.addWidget(self.resetButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.applyButton = QtWidgets.QPushButton(self.gestureTab)
        self.applyButton.setMinimumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.applyButton.setFont(font)
        self.applyButton.setStyleSheet("background-color: rgb(112, 211, 69);")
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout_3.addWidget(self.applyButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 4, 1, 1)
        self.tabWidget.addTab(self.gestureTab, "")
        self.cameraTab = QtWidgets.QWidget()
        self.cameraTab.setObjectName("cameraTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.cameraTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.recognition_in_cameratab_label = QtWidgets.QLabel(self.cameraTab)
        self.recognition_in_cameratab_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recognition_in_cameratab_label.sizePolicy().hasHeightForWidth())
        self.recognition_in_cameratab_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recognition_in_cameratab_label.setFont(font)
        self.recognition_in_cameratab_label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                                          "border: 1px solid black;")
        self.recognition_in_cameratab_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.recognition_in_cameratab_label.setObjectName("recognition_in_cameratab_label")
        self.gridLayout_4.addWidget(self.recognition_in_cameratab_label, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FeedLabel = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.verticalLayout_3.addWidget(self.FeedLabel)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.setResolutionCamera_combobox = QtWidgets.QComboBox(self.cameraTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setResolutionCamera_combobox.sizePolicy().hasHeightForWidth())
        self.setResolutionCamera_combobox.setSizePolicy(sizePolicy)
        self.setResolutionCamera_combobox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                                        "border: 1px solid black;")
        self.setResolutionCamera_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.setResolutionCamera_combobox.setObjectName("setResolutionCamera_combobox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.setResolutionCamera_combobox)
        self.set_resolutionCameras_Button = QtWidgets.QPushButton(self.cameraTab)
        self.set_resolutionCameras_Button.setStyleSheet("background-color: rgb(112, 211, 69);")
        self.set_resolutionCameras_Button.setObjectName("set_resolutionCameras_Button")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.set_resolutionCameras_Button)
        self.refreshCameras_Button = QtWidgets.QPushButton(self.cameraTab)
        self.refreshCameras_Button.setStyleSheet("background-color: rgb(112, 211, 69);")
        self.refreshCameras_Button.setObjectName("refreshCameras_Button")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.refreshCameras_Button)
        self.setCamera_combobox = QtWidgets.QComboBox(self.cameraTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setCamera_combobox.sizePolicy().hasHeightForWidth())
        self.setCamera_combobox.setSizePolicy(sizePolicy)
        self.setCamera_combobox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                              "border: 1px solid black;")
        self.setCamera_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.setCamera_combobox.setObjectName("setCamera_combobox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.setCamera_combobox)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.cameraTab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.action6_comboBox, self.action8_comboBox)
        MainWindow.setTabOrder(self.action8_comboBox, self.action9_comboBox)
        MainWindow.setTabOrder(self.action9_comboBox, self.action3_comboBox)
        MainWindow.setTabOrder(self.action3_comboBox, self.action10_comboBox)
        MainWindow.setTabOrder(self.action10_comboBox, self.action11_comboBox)
        MainWindow.setTabOrder(self.action11_comboBox, self.action20_comboBox)
        MainWindow.setTabOrder(self.action20_comboBox, self.action18_comboBox)
        MainWindow.setTabOrder(self.action18_comboBox, self.action17_comboBox)
        MainWindow.setTabOrder(self.action17_comboBox, self.action16_comboBox)
        MainWindow.setTabOrder(self.action16_comboBox, self.action15_comboBox)
        MainWindow.setTabOrder(self.action15_comboBox, self.action14_comboBox)
        MainWindow.setTabOrder(self.action14_comboBox, self.action13_comboBox)
        MainWindow.setTabOrder(self.action13_comboBox, self.action12_comboBox)
        MainWindow.setTabOrder(self.action12_comboBox, self.action25_comboBox)
        MainWindow.setTabOrder(self.action25_comboBox, self.action24_comboBox)
        MainWindow.setTabOrder(self.action24_comboBox, self.action23_comboBox)
        MainWindow.setTabOrder(self.action23_comboBox, self.action22_comboBox)
        MainWindow.setTabOrder(self.action22_comboBox, self.action21_comboBox)
        MainWindow.setTabOrder(self.action21_comboBox, self.action19_comboBox)
        MainWindow.setTabOrder(self.action19_comboBox, self.action7_comboBox)
        MainWindow.setTabOrder(self.action7_comboBox, self.action5_comboBox)
        MainWindow.setTabOrder(self.action5_comboBox, self.action4_comboBox)
        MainWindow.setTabOrder(self.action4_comboBox, self.action1_comboBox)
        MainWindow.setTabOrder(self.action1_comboBox, self.action2_comboBox)
        MainWindow.setTabOrder(self.action2_comboBox, self.applyButton)
        MainWindow.setTabOrder(self.applyButton, self.cancelButton)
        MainWindow.setTabOrder(self.cancelButton, self.resetButton)

        resolution_list=[[320, 240], [480, 320], [640, 480], [800, 480], [800, 600],
                         [1024, 768], [1280, 720], [1366, 768], [1280, 800], [1366, 768],
                         [1280, 800], [1440, 900], [1280, 1024], [1600, 1024], [1400, 1050],
                         [1024, 600], [1680, 1050], [1600, 1200], [1600, 900], [1920, 1080],]
        self.setResolutionCamera_combobox.addItem("Original")
        for i in resolution_list:
            self.setResolutionCamera_combobox.addItem(str(i[0])+"x"+str(i[1]))
        '''wziecie wszystkich nazw akcji'''
        action_names = self.cont.get_camera().get_mapping().function_getter.get_all_functions_names()
        '''dodanie akcji do comboboxow'''
        for i in action_names:
            self.action1_comboBox.addItem(i)
            self.action2_comboBox.addItem(i)
            self.action3_comboBox.addItem(i)
            self.action4_comboBox.addItem(i)
            self.action5_comboBox.addItem(i)
            self.action6_comboBox.addItem(i)
            self.action7_comboBox.addItem(i)
            self.action8_comboBox.addItem(i)
            self.action9_comboBox.addItem(i)
            self.action10_comboBox.addItem(i)
            self.action11_comboBox.addItem(i)
            self.action12_comboBox.addItem(i)
            self.action13_comboBox.addItem(i)
            self.action14_comboBox.addItem(i)
            self.action15_comboBox.addItem(i)
            self.action16_comboBox.addItem(i)
            self.action17_comboBox.addItem(i)
            self.action18_comboBox.addItem(i)
            self.action19_comboBox.addItem(i)
            self.action20_comboBox.addItem(i)
            self.action21_comboBox.addItem(i)
            self.action22_comboBox.addItem(i)
            self.action23_comboBox.addItem(i)
            self.action24_comboBox.addItem(i)
            self.action25_comboBox.addItem(i)
        self.get_config()
        arr = self.cont.get_camera_controller().get_all_cameras()
        for i in arr:
            self.setCamera_combobox.addItem(str(i))
        self.set_resolutionCameras_Button.clicked.connect(lambda: self.cont.get_camera_controller().set_camera_resolution(self.setResolutionCamera_combobox.currentText()))
        self.refreshCameras_Button.clicked.connect(lambda: self.refresh_camera_list())
        self.authorButton.clicked.connect(lambda: self.show_authors())
        self.documentationButton.clicked.connect(lambda: self.open_documentation())
        self.setCamera_combobox.activated.connect(lambda: self.set_camera())
        self.startHandyButton.clicked.connect(lambda: self.cont.start_gesture_recognition())
        self.stopHandyButton.clicked.connect(lambda: self.cont.stop_gesture_recognition())
        self.applyButton.clicked.connect(lambda: self.set_config())
        self.resetButton.clicked.connect(lambda: self.get_default_config())
        self.cancelButton.clicked.connect(lambda: self.get_config())
        self.Worker1 = Worker1(self.cont,self)
        self.Worker1.start()
        self.Worker1.ImageUpdate.connect(self.ImageUpdateSlot)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Handy", "Handy"))
        self.documentationButton.setText(_translate("MainWindow", "Documentation"))
        self.startHandyButton.setText(_translate("MainWindow", "Start Handy"))
        self.authorButton.setText(_translate("MainWindow", "Authors"))
        self.recognition_in_starttab_label.setText(_translate("MainWindow", "Gesture recognition disabled"))
        self.stopHandyButton.setText(_translate("MainWindow", "Stop Handy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Start"))
        self.recognition_in_gesturetab_label.setText(_translate("MainWindow", "Gesture recognition disabled"))
        self.gesturename_label.setText(_translate("MainWindow", "Gesture name"))
        self.actionNameLabel.setText(_translate("MainWindow", "Action name"))
        self.pull_hand_in_label.setStyleSheet(_translate("MainWindow", "background-color: rgb(79, 79, 79);\n"
                                                                       "background-color: rgb(111, 111, 111);"))
        self.pull_hand_in_label.setText(_translate("MainWindow", "Pulling hand in"))
        self.drumming_fingers_label.setText(_translate("MainWindow", "Drumming fingers"))
        self.pushingTwoFingers_label.setText(_translate("MainWindow", "Pushing two fingers_away"))
        self.pullingTwoFingersfingers_label.setText(_translate("MainWindow", "Pulling two fingers in"))
        self.pushinHandAway_label.setText(_translate("MainWindow", "Pushing hand away"))
        self.rollingHandForward_label.setText(_translate("MainWindow", "Rolling hand forward"))
        self.rollingHandBackward_label.setText(_translate("MainWindow", "Rolling hand backward"))
        self.shakingHand_label.setText(_translate("MainWindow", "Shaking hand"))
        self.sliding2Down_label.setText(_translate("MainWindow", "Sliding two fingers down"))
        self.sliding2left_label.setText(_translate("MainWindow", "Sliding two fingers left"))
        self.sliding2right_label.setText(_translate("MainWindow", "Sliding two fingers right"))
        self.sliding2up_label.setText(_translate("MainWindow", "Sliding two fingers up"))
        self.stopSign_label.setText(_translate("MainWindow", "Stop sign"))
        self.swipingDown_label.setText(_translate("MainWindow", "Swiping down"))
        self.swipingLeft_label.setText(_translate("MainWindow", "Swiping left"))
        self.swipingRight_label.setText(_translate("MainWindow", "Swiping right"))
        self.swipingUp_label.setText(_translate("MainWindow", "Swiping up"))
        self.thumbDown_label.setText(_translate("MainWindow", "Thumb down"))
        self.ThumbUp_label.setText(_translate("MainWindow", "Thumb up"))
        self.turningHandClockwise_label.setText(_translate("MainWindow", "Turning hand clockwise"))
        self.turningHandcounterclockwise_label.setText(_translate("MainWindow", "Turning hand counterclockwise"))
        self.zoomingInWithFull_label.setText(_translate("MainWindow", "Zooming in with full hand"))
        self.zoomingInWith2_label.setText(_translate("MainWindow", "Zoming in with two fingers"))
        self.zoomingOutWithFull_label.setText(_translate("MainWindow", "Zooming out with full hand"))
        self.zoomingOutWith2_label.setText(_translate("MainWindow", "Zooming out with two fingers"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.applyButton.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gestureTab), _translate("MainWindow", "Gestures"))
        self.recognition_in_cameratab_label.setText(_translate("MainWindow", "Gesture recognition disabled"))
        self.FeedLabel.setText(_translate("MainWindow", "TextLabel"))
        self.set_resolutionCameras_Button.setText(_translate("MainWindow", "  Set resolution   "))
        self.refreshCameras_Button.setText(_translate("MainWindow", "Refresh cameras"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cameraTab), _translate("MainWindow", "Camera"))



    def ImageUpdateSlot(self, Image):
        pass
        self.FeedLabel.setPixmap(QPixmap.fromImage(Image))

    def is_active(self):
        return self.cameraTab.isVisible()


class Worker1(QThread):
    def __init__(self, controller, win):
        super().__init__()
        self.controller = controller
        self.win = win
        self.camera = self.controller.get_camera_controller()
    ImageUpdate = pyqtSignal(QImage)

    def run(self):

        while self.win.get_close_time() is False:
            if self.win.is_active():
                pass
                ret, frame = self.camera.get_camera_image()
                if ret is True:
                    Image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                    FlippedImage = cv2.flip(Image, 1)
                    ConvertToQtFormat = QImage(FlippedImage.data, FlippedImage.shape[1], FlippedImage.shape[0],
                                               QImage.Format_RGB888)
                    Pic = ConvertToQtFormat.scaled(720, 540, Qt.KeepAspectRatio)
                    self.ImageUpdate.emit(Pic)
            time.sleep(0.02)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
